{% set name = "libspimage" %}
{% set version = "1.1.dev" %}

package:
  name: libspimage
  version: '1.1.dev'

source:
  git_tag: master
  git_url: https://github.com/FXIhub/libspimage.git
  sha256: 9ac89517061ba80bd941423488945cd219ea742c

requirements:
  build:
    - git
    - cmake
    - {{ compiler('c') }} # [not osx]
    - {{ compiler('cxx') }} # [not osx]
    
  host:
    - python
    - setuptools
    - swig
    - libpng
    - libtiff
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - scipy

  run:
    - python
    - libpng
    - libtiff
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - scipy
    - h5py

test:
  requires:
    - python
    - libpng
    - libtiff
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - scipy
    - h5py
  imports:
    - spimage

about:
  home: https://github.com/FXIhub/libspimage
  license: GPL
  license_file: Copyright
  summary: Phase retrieval library

extra:
  recipe-maintainers:
    - FilipeMaia
