{% set name = "libspimage-gpu" %}
{% set version = "1.1" %}
{% set build = 0 %}

{% set cuda_compiler_version = cuda_compiler_version|default('None') %}

{% if cuda_compiler_version == 'None' %}
# prefer no CUDA builds via a build number offset
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_tag: master
  git_url: https://github.com/FXIhub/libspimage.git
  sha256: c627482e15d3335ef85a72c80ed86c8a808bfe88

build:
  number: {{ build }}
  # CUDA only available for linux
  skip: True  # [osx]
  {% if cuda_compiler_version != 'None' %}
  {% set cuda_prefix = "cuda_" + cuda_compiler_version %}
  {% else %}
  {% set cuda_prefix = "nocuda" %}
  {% endif %}
  string: "{{ cuda_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - git
    - cmake
    - {{ compiler('c') }} # [not osx]
    - {{ compiler('cxx') }} # [not osx]
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    
  host:
    - python
    - setuptools
    - swig
    - libpng
    - libtiff
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - scipy

  run:
    - python
    - libpng
    - libtiff
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - scipy
    - h5py

test:
  requires:
    - python
    - libpng
    - libtiff
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - scipy
    - h5py
  imports:
    - spimage

about:
  home: https://github.com/FXIhub/libspimage
  license: GPL
  license_file: Copyright
  summary: Phase retrieval library

extra:
  recipe-maintainers:
    - FilipeMaia
